import { expect, test } from '@playwright/test';
import { BASE_URL, createPage, publicationCount, db } from './support';
import { OUTPUT_DIR } from './env';
const OUTPUT = (process.env.ARKON_UI_OUT ?? `${OUTPUT_DIR}/seo-ux`) + '/';
test('SEO is discoverable, updates from draft output and publishes real head metadata', async ({ page }) => {
    const id = await createPage('/seo-workflow', 'Our services');
    await page.goto(`/admin/editor/${id}`);
    await page.getByRole('tab', { name: 'SEO', exact: true }).click();
    const panel = page.getByTestId('seo-panel');
    await expect(panel).toBeVisible();
    await expect(page.getByTestId('seo-status')).toContainText(/\d/);
    await page.getByLabel('SEO title', { exact: true }).fill('Our services | Example');
    await page.getByLabel('Meta description', { exact: true }).fill('Explore our services and contact the team to discuss your requirements.');
    await expect(panel).toContainText('100 / 100');
    await expect(panel.getByText('Our services | Example', { exact: true })).toBeVisible();
    await expect(panel.getByRole('paragraph').filter({ hasText: /^Explore our services and contact the team to discuss your requirements\.$/ })).toBeVisible();
    await panel.evaluate((el) => {
        el.closest('.ak-scroll')?.scrollTo(0, 0);
    });
    await expect(page.getByRole('tab', { name: 'SEO', exact: true })).toHaveText('SEO');
    await page.screenshot({ path: OUTPUT + 'SEO editor.png', fullPage: true });
    await page.getByRole('button', { name: 'Save draft', exact: true }).click();
    await expect(page.getByTestId('save-status')).toHaveText('Draft saved');
    expect(await publicationCount(id)).toBe(0);
    await page.getByRole('button', { name: 'Publish', exact: true }).click();
    await expect(page.getByTestId('notice')).toContainText('Published.');
    const response = await page.request.get(BASE_URL + '/seo-workflow');
    const html = await response.text();
    expect(html).toContain('<title>Our services | Example</title>');
    expect(html).toContain('name="description"');
    expect(html).toContain('property="og:title"');
    expect(html).toContain('name="twitter:title"');
    expect(html).toContain('type="application/ld+json"');
    await page.getByRole('button', { name: 'Advanced', exact: true }).click();
    await page.getByLabel('Canonical URL override').fill('https:///broken');
    await page.getByRole('button', { name: 'Publish', exact: true }).click();
    await expect(page.getByTestId('notice')).toContainText('Fix or revert the Canonical URL');
    expect(await publicationCount(id)).toBe(1);
    await page.getByLabel('Canonical URL override').fill('');
    await page.goto('/admin/seo');
    await expect(page.getByRole('heading', { name: 'SEO', exact: true })).toBeVisible();
    const row = page.getByRole('row').filter({ has: page.getByText('seo-workflow', { exact: true }) });
    await expect(row).toContainText('100 — Excellent');
    await row.getByRole('link', { name: 'Review / AI fix' }).click();
    await expect(page.getByTestId('seo-panel')).toBeVisible();
});
test('SEO AI generation is reviewable, projects a real score and uses normal history', async ({ page }) => {
    const id = await createPage('/seo-ai', 'Our services');
    await page.goto(`/admin/editor/${id}?panel=seo`);
    const panel = page.getByTestId('seo-panel');
    await expect(panel).toBeVisible();
    await expect(panel.getByRole('button', { name: 'Improve SEO with AI' })).toBeEnabled();
    await panel.getByRole('button', { name: 'Improve SEO with AI' }).click();
    const proposal = page.getByTestId('ai-proposal');
    await expect(proposal).toContainText('Review accurate search metadata.', { timeout: 30000 });
    await expect(page.getByTestId('seo-projection')).toContainText('Proposed: 100');
    expect((await db.query('select document from page_drafts where page_id=$1', [id])).rows[0].document.seo.description).toBeUndefined();
    await proposal.getByRole('button', { name: /Apply.*draft/i }).click();
    await expect(page.getByTestId('save-status')).toHaveText('Draft saved');
    await page.getByRole('tab', { name: 'SEO', exact: true }).click();
    await expect(page.getByLabel('Meta description', { exact: true })).toHaveValue('Explore our services and contact the team to discuss your requirements.');
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.getByLabel('Meta description', { exact: true })).toHaveValue('');
    expect(await publicationCount(id)).toBe(0);
});
test('SEO dashboard and defaults fit desktop and phone layouts without triggering AI', async ({ page }) => {
    await page.goto('/admin/seo');
    await expect(page.getByRole('heading', { name: 'SEO', exact: true })).toBeVisible();
    await page.screenshot({ path: OUTPUT + 'SEO dashboard.png', fullPage: true });
    await page.getByRole('link', { name: 'Site SEO defaults' }).click();
    await expect(page.getByLabel('Site title pattern')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Save defaults', exact: true })).toBeEnabled();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: OUTPUT + 'SEO defaults mobile.png', fullPage: true });
    await page.goto('/admin/seo');
    await page.screenshot({ path: OUTPUT + 'SEO dashboard mobile.png', fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
