<?php

return [

    /*
    | Databases per target. Every target uses the same server and runtime role;
    | only the database name differs. Tests never touch the dev database.
    */
    'databases' => [
        'dev' => env('ARKON_DB_DEV', 'arkonlaravel'),
        'test' => env('ARKON_DB_TEST', 'arkonlaravel_test'),
        'e2e' => env('ARKON_DB_E2E', 'arkonlaravel_e2e'),
    ],

    /*
    | File with the schema-owner credentials (relative to the project root). Read
    | only by migration tooling and the test harness, never loaded into the
    | environment of the web app.
    */
    'migration_env_file' => '.migrate.env',

    /*
    | Uploaded media. Relative paths are resolved from the project root.
    */
    'media_root' => env('ARKON_MEDIA_ROOT', 'storage/app/media'),

    // Installed developer components are application-wide in this first milestone.
    'theme_source' => base_path('themes'),
    'theme_store' => env('ARKON_THEME_STORE', env('APP_ENV') === 'testing' ? storage_path('framework/testing/theme-components') : storage_path('app/theme-components')),

    'seed_hosts' => env('ARKON_SEED_HOSTS', 'arkonlaravel.test'),

    /*
    | How long the runtime role check is cached between requests (seconds).
    */
    'runtime_check_ttl' => 300,

    /*
    | AI page proposals, generated by Claude Code under your own Claude subscription:
    | - in Claude Code (VS Code) through Arkon's MCP server (`php artisan arkon:mcp`), or
    | - from the editor's AI panel through the local helper (`php artisan arkon:ai-helper`),
    |   which runs the Claude Code CLI. There is no API key and no paid API path.
    | Claude Code enforces your subscription's own usage limits; the limits below only bound
    | how often and how many requests Arkon starts.
    */
    'ai' => [
        // The Claude Code CLI for the helper: a path, or a JSON array (e.g. ["node","fake.mjs"]).
        // Empty: claude.exe on PATH, then ~/.local/bin, then the newest VS Code extension binary.
        'claude_command' => env('ARKON_CLAUDE_COMMAND'),
        // Optional model alias for the helper's runs (sonnet, opus, ...); empty uses Claude Code's default.
        'model' => env('ARKON_AI_MODEL'),
        'min_claude_version' => '2.1.259',
        // One Claude Code run (including a repair run) is stopped after this long.
        'run_timeout_seconds' => (int) env('ARKON_AI_RUN_TIMEOUT', 240),
        // A running request is leased to one helper; the lease is renewed while Claude works.
        'lease_seconds' => 45,
        // Runs per request when a helper stops mid-run (helper restart recovery), and repair runs.
        'max_attempts' => 2,
        'repair_attempts' => 1,
        // A queued request nobody picks up fails after this long.
        'queue_timeout_seconds' => 300,
        // A helper that has not reported for this long counts as disconnected.
        'helper_stale_seconds' => 20,
        'prompt_max_chars' => 2000,
        'max_changes' => 40,
        'per_user_per_minute' => (int) env('ARKON_AI_PER_USER_PER_MINUTE', 5),
        'per_site_per_day' => (int) env('ARKON_AI_PER_SITE_PER_DAY', 100),
        // Requests queued or running at once, per site.
        'max_active_per_site' => (int) env('ARKON_AI_MAX_ACTIVE_PER_SITE', 2),
        // Where `arkon:ai-pair --helper` saves the helper's token (git-ignored storage).
        'helper_token_file' => env('ARKON_HELPER_TOKEN_FILE') ?: storage_path('app/private/ai-helper.token'),
    ],

];
